langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${openai.api-key}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${openai.api-key}
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
      #embedding model配置
      #向量数据库配置
#  community:
#    redis:
#      host: localhost
#      port: 6399
#      dimension: 1024
#  ollama:
#    embedding-model:
#      base-url: http://localhost:11434
#      model-name: bge-m3

logging:
  level:
    dev.langchain4j: debug
spring:
  data:
    redis:
      host: localhost
      port: 6379
